export const WEDDING_CONFIG = {
  bride: "Michelle",
  groom: "Marcing",
  title: "Mariage civil, religieux & traditionnel",
  dateString: "26 décembre 2026",
  dateIso: "2026-12-26T13:00:00+01:00",
  locationName: "Mission protestante de Nlem, Bandjoun",
  city: "Bandjoun, Cameroun",
  directions: "Depuis le Centre climatique de Bandjoun, prenez la moto et dites simplement : « Mission protestante de Nlem ». La maison est juste à côté.",
  rsvpDeadline: "1er décembre 2026",
  quote: "« Le mariage, c'est la volonté à deux de créer l'unique. »",
  quoteAuthor: "Friedrich Nietzsche",
  story:
    "On dit que chacun a sa moitié, mais seuls les plus chanceux la rencontrent. Nous nous sentons bénis d’avoir eu la chance de nous trouver. C’est avec une joie immense et le cœur comblé que nous vous convions à la célébration de notre mariage : civil, religieux et traditionnel.",
  gifts: {
    title: "Dons et cadeaux",
    intro: "Votre présence à nos côtés est déjà le plus beau des cadeaux. Si vous souhaitez nous témoigner votre affection par un don, nous le recevrons avec joie et gratitude.",
    recipient: "Kapche Michelle",
    numbers: ["688915296", "651974889"],
    closing: "Avec toute notre gratitude, Michelle et Marcing",
  },
  assets: {
    heroCouple: "/manus-storage/heroCouple_5ac207a9.webp",
    groomPortrait: "/manus-storage/groomPortrait_26f308fc.webp",
    bridePortrait: "/manus-storage/bridePortrait_3ce3385c.webp",
    presents: "/manus-storage/presents_ca130746.webp",
    handsUnion: "/manus-storage/handsUnion_c4f9e4b6.webp",
    tableSetting: "/manus-storage/tableSetting_b7b3883f.webp",
    bandjounLandscape: "/manus-storage/bafoussamLandscape_5dc0e47c.webp",
    buffetAtmosphere: "/manus-storage/buffetAtmosphere_b403f404.webp",
    flowersBanner: "/manus-storage/flowersBanner_8d4a287e.webp",
    videoPoster: "/manus-storage/videoPoster_40bb41ea.webp",
    videoUrl: "/manus-storage/video_mariage_1080p_avec_son_2a4f704e.mp4",
  },
  schedule: [
    {
      start: "13 h 00",
      end: "14 h 00",
      title: "Cérémonie de mariage civil",
      description: "Échange des consentements devant l'officier d'état civil, entourés de nos familles et témoins.",
      icon: "civil",
    },
    {
      start: "14 h 00",
      end: "14 h 30",
      title: "Prise des photos",
      description: "Séance photo avec les mariés, les familles et les amis pour immortaliser ce premier grand moment.",
      icon: "photo",
    },
    {
      start: "14 h 30",
      end: "18 h 30",
      title: "Vin d'honneur",
      description: "Un moment convivial pour trinquer, échanger et partager notre joie autour d'un rafraîchissement.",
      icon: "toast",
    },
    {
      start: "18 h 30",
      end: "20 h 00",
      title: "Déplacement vers le lieu de la cérémonie traditionnelle",
      description: "Tous en route ensemble vers le lieu de la célébration traditionnelle.",
      icon: "travel",
    },
    {
      start: "20 h 00",
      end: "21 h 30",
      title: "Célébration eucharistique",
      description: "Bénédiction de notre union devant Dieu, dans la prière et l'action de grâce.",
      icon: "church",
    },
    {
      start: "21 h 30",
      end: "22 h 00",
      title: "Pause",
      description: "Une courte pause pour se rafraîchir avant la suite des festivités.",
      icon: "break",
    },
    {
      start: "22 h 00",
      end: "02 h 00",
      title: "Célébration traditionnelle",
      description: "Union selon nos coutumes, bénédiction des familles et scellement de notre alliance dans la tradition.",
      icon: "tradition",
    },
    {
      start: "02 h 00",
      end: "",
      title: "Réjouissances",
      description: "Danses, musique et fête jusqu'au bout de la nuit !",
      icon: "party",
    },
  ],
};
