export const WEDDING_CONFIG = {
  bride: "Michelle",
  groom: "Marcing",
  title: "Mairie, église & soirée",
  dateString: "26 décembre 2026",
  dateLong: "Samedi 26 décembre 2026",
  dateIso: "2026-12-26T13:00:00+01:00",
  locationName: "Paroisse Christ Sauveur de Mbangué",
  city: "Douala, Cameroun",
  directions: "Au carrefour Toiture Rouge, à Mbangué.",
  placesNote: "Les adresses précises de la mairie et de la soirée vous seront communiquées dès qu’elles seront confirmées.",
  rsvpDeadline: "1er décembre 2026",
  quote: "« Que tout ce que vous faites se fasse avec amour. »",
  quoteAuthor: "1 Corinthiens 16:14",
  story:
    "Il y a eu un premier regard, puis une conversation qui ne voulait pas finir. Depuis, chaque jour nous rapproche un peu plus. Aujourd’hui, nous avons envie de dire oui, devant nos familles, devant Dieu et entourés de vous.",
  brideWords: "« Il a cette façon de me faire rire quand je doute, et de me faire sentir chez moi partout où il est. »",
  groomWords: "« Elle est ma paix, ma plus belle prière exaucée et la complice de tous mes lendemains. »",
  gifts: {
    title: "Dons et cadeaux",
    intro: "Vos prières et votre présence à nos côtés sont déjà le plus beau des cadeaux.",
    recipient: "Kapche Michelle",
    numbers: ["688915296", "651974889"],
    interac: "kusstella@gmail.com",
    closing: "Avec toute notre gratitude, Michelle & Marcing",
  },
  assets: {
    heroCouple: "/manus-storage/heroCouple_natural_66342999.webp",
    groomPortrait: "/manus-storage/groomPortrait_clean_31fe7619.webp",
    bridePortrait: "/manus-storage/bridePortrait_3ce3385c.webp",
    presents: "/manus-storage/presents_ca130746.webp",
    handsUnion: "/manus-storage/handsUnion_c4f9e4b6.webp",
    tableSetting: "/manus-storage/tableSetting_b7b3883f.webp",
    bandjounLandscape: "/manus-storage/bafoussamLandscape_5dc0e47c.webp",
    buffetAtmosphere: "/manus-storage/buffetAtmosphere_b403f404.webp",
    flowersBanner: "/manus-storage/flowersBanner_8d4a287e.webp",
    videoPoster: "/manus-storage/videoPoster_40bb41ea.webp",
    videoUrl: "/manus-storage/video_mariage_1080p_avec_son_2a4f704e.mp4",
  },
  schedule: [
    {
      id: "civil",
      start: "13 h 00",
      end: "",
      title: "Le oui à la mairie",
      location: "Mairie — adresse communiquée bientôt",
      description: "Devant l’officier d’état civil, entourés de nos témoins et de nos familles, nous échangerons nos consentements.",
      icon: "civil",
      confirmed: false,
    },
    {
      id: "church",
      start: "15 h 00",
      end: "",
      title: "La messe d’action de grâce",
      location: "Paroisse Christ Sauveur de Mbangué, au carrefour Toiture Rouge",
      description: "Nous rendrons grâce à Dieu pour notre union, dans la prière et la joie, avec vous à nos côtés.",
      icon: "church",
      confirmed: true,
    },
    {
      id: "party",
      start: "20 h 00",
      end: "",
      title: "La soirée",
      location: "Salle de réception — adresse communiquée bientôt",
      description: "Place à la fête : un bon repas, de la musique, des danses et beaucoup d’amour jusqu’au bout de la nuit.",
      icon: "party",
      confirmed: false,
    },
  ],
};
